### ISSUE TITLE
Unexpected Error - Plugin Fails to Load

### ISSUE THREAD

**Issue by TraipsingShadow** [Tweetzy/Vouchers#24]
**Describe the bug**
I couldn't really describe it apart from the fact that the plugin fails to load.

**To Reproduce**
- Describe how to reproduce this bug:

1. Launch server
2. Vouchers plugin fails to load

**Expected behavior**
Plugin loads successfully.

**Server Error Log**
```
ca.tweetzy.vouchers.flight.third_party.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.Yaml.load(Yaml.java:430) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.config.yaml.YamlConfiguration.load(YamlConfiguration.java:214) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.config.tweetzy.TweetzyYamlConfig.load(TweetzyYamlConfig.java:183) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.config.tweetzy.TweetzyYamlConfig.load(TweetzyYamlConfig.java:164) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.config.tweetzy.TweetzyYamlConfig.init(TweetzyYamlConfig.java:107) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.settings.FlightTranslator.setup(FlightTranslator.java:120) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.settings.Translations.init(Translations.java:81) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.Vouchers.onFlight(Vouchers.java:64) ~[Vouchers.jar:?]
        at ca.tweetzy.vouchers.flight.FlightPlugin.onEnable(FlightPlugin.java:91) ~[Vouchers.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-431]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-431]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.io.BufferedReader.read1(BufferedReader.java:213) ~[?:?]
        at java.io.BufferedReader.read(BufferedReader.java:287) ~[?:?]
        at ca.tweetzy.vouchers.flight.third_party.snakeyaml.reader.StreamReader.update(StreamReader.java:176) ~[Vouchers.jar:?]
        ... 33 more
```

**Server Information (please complete the following information):**
_Minecraft_ Version: `1.19.3`
Server Software and Version: `paper-1.19.3-431`
Plugin Version: `3.9.0`

**Additional context**
N/A

**Comment by kiranhart** [comment]
Deleting the config and lang files should resolve the issue. Re-Open if it still persists
